# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: itGlee - Agile with a Smile Solutions
email: info@itglee.com
site: https://www.itglee.com
phone: (+351) 233 094 915
address: Rua Diogo Cão, 34<br />3080-318 Figueira da Foz<br /> Portugal
description: asdas
baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

domain: fmatitglee.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://fmatitglee.github.io/itGlee  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /itGlee/      # place folder name if the site is served in a subfolder
formSpreeKey: mwkdgzvz

apikey: u7oRbTSh9VE5fw29eRD4wbsUwo
# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  posts:
    output: true
  socials:
    output: true
    sort_by: order
  awards:
    output: true
  partners:
    output: true
    sort_by: order
  sections:
    output: true
    sort_by: order
  services:
    output: true
    sort_by: order
  menuitems:
    output: true
    sort_by: order
  openpositions:
    output: true
    sort_by: order

permalinks:
